services:
  app:
    image: chat-app

    networks:
      - backend-network

    ports:
      - "8080:8080"

    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  mongo-data:
  postgres-data:

networks:
  backend-network:
    driver: overlay
    attachable: true