spring:
  application:
    name: chat

  profiles:
    active: mongo

  docker:
    compose:
      enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/chat



logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharactersLong!
  expiration: 86400000