spring:
  application:
    name: chat

  profiles:
    active: mongo

  docker:
    compose:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharactersLong!
  expiration: 86400000