spring:
  application:
    name: chat
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: mongo

  docker:
    compose:
      enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/chat}



logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharactersLong!
  expiration: 86400000

keycloak:
  url: ${KEYCLOAK_URL:http://localhost:9090}
  realm: ${KEYCLOAK_REALM:chat}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
